const COUNTRY_NAMES = [
  'Afganistan', 'Albania', 'Algieria', 'Andora', 'Angola', 'Argentyna', 'Armenia', 'Australia',
  'Austria', 'Azerbejdżan', 'Bahamy', 'Bahrajn', 'Bangladesz', 'Barbados', 'Belgia', 'Belize',
  'Benin', 'Bhutan', 'Boliwia', 'Bośnia i Hercegowina', 'Botswana', 'Brazylia', 'Brunei',
  'Bułgaria', 'Burkina Faso', 'Burundi', 'Chile', 'Chiny', 'Chorwacja', 'Cypr', 'Czechy',
  'Dania', 'Dominikana', 'Dżibuti', 'Egipt', 'Ekwador', 'Erytrea', 'Estonia', 'Eswatini',
  'Etiopia', 'Fidżi', 'Filipiny', 'Finlandia', 'Francja', 'Gabon', 'Gambia', 'Ghana', 'Grecja',
  'Grenada', 'Gruzja', 'Guam', 'Gujana', 'Gwatemala', 'Gwinea', 'Gwinea Bissau',
  'Gwinea Równikowa', 'Haiti', 'Hiszpania', 'Holandia', 'Honduras', 'Indie', 'Indonezja',
  'Irak', 'Iran', 'Irlandia', 'Islandia', 'Izrael', 'Jamajka', 'Japonia', 'Jemen', 'Jordania',
  'Kambodża', 'Kamerun', 'Kanada', 'Katar', 'Kazachstan', 'Kenia', 'Kirgistan', 'Kolumbia',
  'Komory', 'Kongo', 'Korea Południowa', 'Korea Północna', 'Kostaryka', 'Kuba', 'Kuwejt',
  'Laos', 'Lesotho', 'Liban', 'Liberia', 'Libia', 'Liechtenstein', 'Litwa', 'Luksemburg',
  'Łotwa', 'Macedonia Północna', 'Madagaskar', 'Malawi', 'Malediwy', 'Malezja', 'Mali',
  'Malta', 'Maroko', 'Mauretania', 'Meksyk', 'Mikronezja', 'Mołdawia', 'Monako', 'Mongolia',
  'Mozambik', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Niemcy', 'Niger', 'Nigeria',
  'Nikaragua', 'Norwegia', 'Nowa Zelandia', 'Oman', 'Pakistan', 'Palau', 'Panama',
  'Papua-Nowa Gwinea', 'Paragwaj', 'Peru', 'Polska', 'Portugalia',
  'Republika Południowej Afryki', 'Republika Środkowoafrykańska', 'Rumunia', 'Rosja',
  'Rwanda', 'Saint Kitts i Nevis', 'Saint Lucia', 'Saint Vincent i Grenadyny', 'Salwador',
  'Samoa', 'San Marino', 'Senegal', 'Serbia', 'Seszele', 'Sierra Leone', 'Singapur',
  'Słowacja', 'Słowenia', 'Somalia', 'Sri Lanka', 'Sudan', 'Sudan Południowy', 'Surinam',
  'Syria', 'Szwajcaria', 'Szwecja', 'Tadżykistan', 'Tajlandia', 'Tanzania', 'Timor Wschodni',
  'Togo', 'Tonga', 'Trynidad i Tobago', 'Tunezja', 'Turcja', 'Turkmenistan', 'Tuvalu',
  'Uganda', 'Ukraina', 'Urugwaj', 'USA', 'Uzbekistan', 'Vanuatu', 'Wenezuela', 'Węgry',
  'Wielka Brytania', 'Wietnam', 'Włochy', 'Wybrzeże Kości Słoniowej', 'Wyspy Marshalla',
  'Wyspy Salomona', 'Zambia', 'Zimbabwe',
] as const;

export const COUNTRY_OPTIONS = COUNTRY_NAMES.map((name) => ({ title: name, value: name }));
