import { defineArrayMember, defineField, defineType } from 'sanity';

export const photoType = defineType({
  name: 'photo',
  title: 'Zdjęcie',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Tytuł zdjęcia',
      type: 'string',
      validation: (Rule) => Rule.required().min(2),
    }),
    defineField({
      name: 'image',
      title: 'Plik zdjęcia',
      type: 'image',
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Kategorie',
      type: 'array',
      description: 'Zaznacz jedną lub więcej kategorii.',
      of: [defineArrayMember({ type: 'string' })],
      options: {
        list: [
          { title: 'Wyprawy Moto', value: 'ADV' },
          { title: 'Podróże', value: 'Travel' },
          { title: 'Natura', value: 'Nature' },
          { title: 'Street', value: 'Street' },
          { title: 'Ślubne', value: 'Wedding' },
          { title: 'Sport', value: 'Sports' },
        ],
      },
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'country',
      title: 'Kraj',
      type: 'string',
      description: 'Zacznij wpisywać kraj, np. „Kam” i wybierz Kambodżę. Pozostaw puste, jeśli zdjęcie nie ma być na mapie.',
      options: {
        list: [
          { title: 'Afganistan', value: 'Afganistan' },
          { title: 'Albania', value: 'Albania' },
          { title: 'Algieria', value: 'Algieria' },
          { title: 'Andora', value: 'Andora' },
          { title: 'Angola', value: 'Angola' },
          { title: 'Argentyna', value: 'Argentyna' },
          { title: 'Armenia', value: 'Armenia' },
          { title: 'Australia', value: 'Australia' },
          { title: 'Austria', value: 'Austria' },
          { title: 'Azerbejdżan', value: 'Azerbejdżan' },
          { title: 'Bahamy', value: 'Bahamy' },
          { title: 'Bahrajn', value: 'Bahrajn' },
          { title: 'Bangladesz', value: 'Bangladesz' },
          { title: 'Barbados', value: 'Barbados' },
          { title: 'Belgia', value: 'Belgia' },
          { title: 'Belize', value: 'Belize' },
          { title: 'Benin', value: 'Benin' },
          { title: 'Bhutan', value: 'Bhutan' },
          { title: 'Boliwia', value: 'Boliwia' },
          { title: 'Bośnia i Hercegowina', value: 'Bośnia i Hercegowina' },
          { title: 'Botswana', value: 'Botswana' },
          { title: 'Brazylia', value: 'Brazylia' },
          { title: 'Brunei', value: 'Brunei' },
          { title: 'Bułgaria', value: 'Bułgaria' },
          { title: 'Burkina Faso', value: 'Burkina Faso' },
          { title: 'Burundi', value: 'Burundi' },
          { title: 'Chile', value: 'Chile' },
          { title: 'Chiny', value: 'Chiny' },
          { title: 'Chorwacja', value: 'Chorwacja' },
          { title: 'Cypr', value: 'Cypr' },
          { title: 'Czechy', value: 'Czechy' },
          { title: 'Dania', value: 'Dania' },
          { title: 'Dominikana', value: 'Dominikana' },
          { title: 'Dżibuti', value: 'Dżibuti' },
          { title: 'Egipt', value: 'Egipt' },
          { title: 'Ekwador', value: 'Ekwador' },
          { title: 'Erytrea', value: 'Erytrea' },
          { title: 'Estonia', value: 'Estonia' },
          { title: 'Eswatini', value: 'Eswatini' },
          { title: 'Etiopia', value: 'Etiopia' },
          { title: 'Fidżi', value: 'Fidżi' },
          { title: 'Filipiny', value: 'Filipiny' },
          { title: 'Finlandia', value: 'Finlandia' },
          { title: 'Francja', value: 'Francja' },
          { title: 'Gabon', value: 'Gabon' },
          { title: 'Gambia', value: 'Gambia' },
          { title: 'Ghana', value: 'Ghana' },
          { title: 'Grecja', value: 'Grecja' },
          { title: 'Grenada', value: 'Grenada' },
          { title: 'Gruzja', value: 'Gruzja' },
          { title: 'Guam', value: 'Guam' },
          { title: 'Gujana', value: 'Gujana' },
          { title: 'Gwatemala', value: 'Gwatemala' },
          { title: 'Gwinea', value: 'Gwinea' },
          { title: 'Gwinea Bissau', value: 'Gwinea Bissau' },
          { title: 'Gwinea Równikowa', value: 'Gwinea Równikowa' },
          { title: 'Haiti', value: 'Haiti' },
          { title: 'Hiszpania', value: 'Hiszpania' },
          { title: 'Holandia', value: 'Holandia' },
          { title: 'Honduras', value: 'Honduras' },
          { title: 'Indie', value: 'Indie' },
          { title: 'Indonezja', value: 'Indonezja' },
          { title: 'Irak', value: 'Irak' },
          { title: 'Iran', value: 'Iran' },
          { title: 'Irlandia', value: 'Irlandia' },
          { title: 'Islandia', value: 'Islandia' },
          { title: 'Izrael', value: 'Izrael' },
          { title: 'Jamajka', value: 'Jamajka' },
          { title: 'Japonia', value: 'Japonia' },
          { title: 'Jemen', value: 'Jemen' },
          { title: 'Jordania', value: 'Jordania' },
          { title: 'Kambodża', value: 'Kambodża' },
          { title: 'Kamerun', value: 'Kamerun' },
          { title: 'Kanada', value: 'Kanada' },
          { title: 'Katar', value: 'Katar' },
          { title: 'Kazachstan', value: 'Kazachstan' },
          { title: 'Kenia', value: 'Kenia' },
          { title: 'Kirgistan', value: 'Kirgistan' },
          { title: 'Kolumbia', value: 'Kolumbia' },
          { title: 'Komory', value: 'Komory' },
          { title: 'Kongo', value: 'Kongo' },
          { title: 'Korea Południowa', value: 'Korea Południowa' },
          { title: 'Korea Północna', value: 'Korea Północna' },
          { title: 'Kostaryka', value: 'Kostaryka' },
          { title: 'Kuba', value: 'Kuba' },
          { title: 'Kuwejt', value: 'Kuwejt' },
          { title: 'Laos', value: 'Laos' },
          { title: 'Lesotho', value: 'Lesotho' },
          { title: 'Liban', value: 'Liban' },
          { title: 'Liberia', value: 'Liberia' },
          { title: 'Libia', value: 'Libia' },
          { title: 'Liechtenstein', value: 'Liechtenstein' },
          { title: 'Litwa', value: 'Litwa' },
          { title: 'Luksemburg', value: 'Luksemburg' },
          { title: 'Łotwa', value: 'Łotwa' },
          { title: 'Macedonia Północna', value: 'Macedonia Północna' },
          { title: 'Madagaskar', value: 'Madagaskar' },
          { title: 'Malawi', value: 'Malawi' },
          { title: 'Malediwy', value: 'Malediwy' },
          { title: 'Malezja', value: 'Malezja' },
          { title: 'Mali', value: 'Mali' },
          { title: 'Malta', value: 'Malta' },
          { title: 'Maroko', value: 'Maroko' },
          { title: 'Mauretania', value: 'Mauretania' },
          { title: 'Meksyk', value: 'Meksyk' },
          { title: 'Mikronezja', value: 'Mikronezja' },
          { title: 'Mołdawia', value: 'Mołdawia' },
          { title: 'Monako', value: 'Monako' },
          { title: 'Mongolia', value: 'Mongolia' },
          { title: 'Mozambik', value: 'Mozambik' },
          { title: 'Myanmar', value: 'Myanmar' },
          { title: 'Namibia', value: 'Namibia' },
          { title: 'Nauru', value: 'Nauru' },
          { title: 'Nepal', value: 'Nepal' },
          { title: 'Niemcy', value: 'Niemcy' },
          { title: 'Niger', value: 'Niger' },
          { title: 'Nigeria', value: 'Nigeria' },
          { title: 'Nikaragua', value: 'Nikaragua' },
          { title: 'Norwegia', value: 'Norwegia' },
          { title: 'Nowa Zelandia', value: 'Nowa Zelandia' },
          { title: 'Oman', value: 'Oman' },
          { title: 'Pakistan', value: 'Pakistan' },
          { title: 'Palau', value: 'Palau' },
          { title: 'Panama', value: 'Panama' },
          { title: 'Papua-Nowa Gwinea', value: 'Papua-Nowa Gwinea' },
          { title: 'Paragwaj', value: 'Paragwaj' },
          { title: 'Peru', value: 'Peru' },
          { title: 'Polska', value: 'Polska' },
          { title: 'Portugalia', value: 'Portugalia' },
          { title: 'Republika Południowej Afryki', value: 'Republika Południowej Afryki' },
          { title: 'Republika Środkowoafrykańska', value: 'Republika Środkowoafrykańska' },
          { title: 'Rumunia', value: 'Rumunia' },
          { title: 'Rosja', value: 'Rosja' },
          { title: 'Rwanda', value: 'Rwanda' },
          { title: 'Saint Kitts i Nevis', value: 'Saint Kitts i Nevis' },
          { title: 'Saint Lucia', value: 'Saint Lucia' },
          { title: 'Saint Vincent i Grenadyny', value: 'Saint Vincent i Grenadyny' },
          { title: 'Salwador', value: 'Salwador' },
          { title: 'Samoa', value: 'Samoa' },
          { title: 'San Marino', value: 'San Marino' },
          { title: 'Senegal', value: 'Senegal' },
          { title: 'Serbia', value: 'Serbia' },
          { title: 'Seszele', value: 'Seszele' },
          { title: 'Sierra Leone', value: 'Sierra Leone' },
          { title: 'Singapur', value: 'Singapur' },
          { title: 'Słowacja', value: 'Słowacja' },
          { title: 'Słowenia', value: 'Słowenia' },
          { title: 'Somalia', value: 'Somalia' },
          { title: 'Sri Lanka', value: 'Sri Lanka' },
          { title: 'Sudan', value: 'Sudan' },
          { title: 'Sudan Południowy', value: 'Sudan Południowy' },
          { title: 'Surinam', value: 'Surinam' },
          { title: 'Syria', value: 'Syria' },
          { title: 'Szwajcaria', value: 'Szwajcaria' },
          { title: 'Szwecja', value: 'Szwecja' },
          { title: 'Tadżykistan', value: 'Tadżykistan' },
          { title: 'Tajlandia', value: 'Tajlandia' },
          { title: 'Tanzania', value: 'Tanzania' },
          { title: 'Timor Wschodni', value: 'Timor Wschodni' },
          { title: 'Togo', value: 'Togo' },
          { title: 'Tonga', value: 'Tonga' },
          { title: 'Trynidad i Tobago', value: 'Trynidad i Tobago' },
          { title: 'Tunezja', value: 'Tunezja' },
          { title: 'Turcja', value: 'Turcja' },
          { title: 'Turkmenistan', value: 'Turkmenistan' },
          { title: 'Tuvalu', value: 'Tuvalu' },
          { title: 'Uganda', value: 'Uganda' },
          { title: 'Ukraina', value: 'Ukraina' },
          { title: 'Urugwaj', value: 'Urugwaj' },
          { title: 'USA', value: 'USA' },
          { title: 'Uzbekistan', value: 'Uzbekistan' },
          { title: 'Vanuatu', value: 'Vanuatu' },
          { title: 'Wenezuela', value: 'Wenezuela' },
          { title: 'Węgry', value: 'Węgry' },
          { title: 'Wielka Brytania', value: 'Wielka Brytania' },
          { title: 'Wietnam', value: 'Wietnam' },
          { title: 'Włochy', value: 'Włochy' },
          { title: 'Wybrzeże Kości Słoniowej', value: 'Wybrzeże Kości Słoniowej' },
          { title: 'Wyspy Marshalla', value: 'Wyspy Marshalla' },
          { title: 'Wyspy Salomona', value: 'Wyspy Salomona' },
          { title: 'Zambia', value: 'Zambia' },
          { title: 'Zimbabwe', value: 'Zimbabwe' },
        ],
      },
    }),
    defineField({
      name: 'location',
      title: 'Lokalizacja (Miasto / region)',
      type: 'string',
      description: 'Opcjonalnie doprecyzuj miejsce, np. miasto lub region.',
    }),
    defineField({
      name: 'exif',
      title: 'Dane sprzętowe (EXIF)',
      type: 'object',
      fields: [
        defineField({ name: 'camera', title: 'Aparat', type: 'string', initialValue: 'Nikon D7100' }),
        defineField({ name: 'lens', title: 'Obiektyw', type: 'string' }),
        defineField({ name: 'aperture', title: 'Przysłona (np. f/1.8)', type: 'string' }),
        defineField({ name: 'speed', title: 'Czas migawki (np. 1/500s)', type: 'string' }),
        defineField({ name: 'iso', title: 'ISO', type: 'string' }),
      ],
    }),
  ],
  preview: {
    select: {
      title: 'title',
      category: 'category',
      media: 'image',
    },
    prepare(selection) {
      const { title, category, media } = selection as {
        title?: string;
        category?: string | string[];
        media?: string | null;
      };
      const subtitle = Array.isArray(category)
        ? category.join(', ')
        : typeof category === 'string'
          ? category
          : 'Brak kategorii';

      return {
        title,
        subtitle,
        media,
      };
    },
  },
});

export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: 'Ustawienia strony',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Nazwa strony',
      type: 'string',
      initialValue: 'Photo Journal',
      validation: (Rule) => Rule.required().min(2),
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline / nagłówek',
      type: 'string',
      initialValue: 'Uchwycić Ulotne',
    }),
    defineField({
      name: 'heroTitle',
      title: 'Tytuł hero',
      type: 'string',
      initialValue: 'Świat przez obiektyw Nikona.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Opis hero',
      type: 'text',
      rows: 4,
      initialValue: 'Niezawodowe kadry. Osobiste historie. Od ryków motocykli ADV, przez rytm Capoeiry, aż po ciszę makro i chaos ulic Tajlandii.',
    }),
    defineField({
      name: 'heroCtaLabel',
      title: 'Tekst przycisku CTA',
      type: 'string',
      initialValue: 'Odkryj Galerię',
    }),
    defineField({
      name: 'heroImage',
      title: 'Zdjęcie w hero',
      type: 'image',
      options: { hotspot: true },
    }),
    defineField({
      name: 'aboutTitle',
      title: 'Nagłówek sekcji O mnie',
      type: 'string',
      initialValue: 'O mnie & Pasje',
    }),
    defineField({
      name: 'aboutDescription',
      title: 'Treść sekcji O mnie',
      type: 'array',
      of: [defineArrayMember({ type: 'block' })],
    }),
    defineField({
      name: 'aboutImage',
      title: 'Zdjęcie w sekcji O mnie',
      type: 'image',
      options: { hotspot: true },
    }),
    defineField({
      name: 'aboutEquipment',
      title: 'Sprzęt / obiektyw',
      type: 'string',
      initialValue: 'Nikon D7100 · Nikkor 35mm f/1.8',
    }),
    defineField({
      name: 'aboutSecondaryText',
      title: 'Dodatkowy opis',
      type: 'text',
      rows: 4,
      initialValue: 'Fotografuję Nikonem D7100. Nie zawodowo, lecz z potrzeby serca. Zatrzymuję chwile, które mają znaczenie.',
    }),
    defineField({
      name: 'footerText',
      title: 'Tekst w stopce',
      type: 'string',
      initialValue: '© 2026 Wszelkie prawa zastrzeżone.',
    }),
  ],
  preview: {
    prepare() {
      return {
        title: 'Ustawienia strony',
      };
    },
  },
});

export const storyType = defineType({
  name: 'story',
  title: 'Historia',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Tytuł historii',
      type: 'string',
      validation: (Rule) => Rule.required().min(2),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title' },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'excerpt',
      title: 'Krótki opis',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'body',
      title: 'Treść historii',
      type: 'array',
      of: [defineArrayMember({ type: 'block' })],
    }),
    defineField({
      name: 'image',
      title: 'Zdjęcie historii',
      type: 'image',
      options: { hotspot: true },
    }),
    defineField({
      name: 'publishedAt',
      title: 'Data publikacji',
      type: 'datetime',
      initialValue: new Date().toISOString(),
    }),
    defineField({
      name: 'category',
      title: 'Kategoria',
      type: 'string',
      options: {
        list: [
          { title: 'Motocykl', value: 'Moto' },
          { title: 'Podróże', value: 'Travel' },
          { title: 'Natura', value: 'Nature' },
          { title: 'Capoeira', value: 'Capoeira' },
          { title: 'Ludzie', value: 'People' },
        ],
      },
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'category',
      media: 'image',
    },
  },
});

export const schemaTypes = [photoType, siteSettingsType, storyType];